#pragma once

#include <skyscraper.h>

#include <toolkit/graphics/2d/ngui/NGuiAnimationEvent.h>
#include <toolkit/graphics/2d/ngui/TkNGuiDraggable.h>
#include <toolkit/graphics/2d/ngui/TkNGuiInput.h>
#include <toolkit/graphics/2d/ngui/TkNGuiUndoable.h>
#include <toolkit/maths/geometry/TkBBox2d.h>

#include <graphics/ngui/metadata/gcnguielementdata.meta.h>
#include <graphics/ngui/metadata/gcnguilayoutdata.meta.h>
#include <graphics/ngui/metadata/gcnguipreset.meta.h>

SKYSCRAPER_BEGIN

enum eNGuiEditorIcons
{
    EIcon_adn                     = 0x61,
    EIcon_aid_medkit_case         = 0x62,
    EIcon_align_center            = 0x63,
    EIcon_align_justify           = 0x64,
    EIcon_align_justify_1         = 0x65,
    EIcon_align_left              = 0x66,
    EIcon_align_right             = 0x67,
    EIcon_ambulance               = 0x68,
    EIcon_anchor                  = 0x69,
    EIcon_android                 = 0x6A,
    EIcon_angle_double_down       = 0x6B,
    EIcon_angle_double_left       = 0x6C,
    EIcon_angle_double_right      = 0x6D,
    EIcon_angle_double_up         = 0x6E,
    EIcon_angle_down              = 0x6F,
    EIcon_angle_left              = 0x70,
    EIcon_angle_right             = 0x71,
    EIcon_angle_up                = 0x72,
    EIcon_apple                   = 0x73,
    EIcon_archive                 = 0x74,
    EIcon_arrow_circle_down       = 0x75,
    EIcon_arrow_circle_down_line  = 0x76,
    EIcon_arrow_circle_left       = 0x77,
    EIcon_arrow_circle_right      = 0x78,
    EIcon_arrow_circle_right_line = 0x79,
    EIcon_arrow_circle_up         = 0x7A,
    EIcon_arrow_circle_up_line    = 0x41,
    EIcon_arrow_down              = 0x42,
    EIcon_arrow_down_1            = 0x43,
    EIcon_arrow_horizontal        = 0x44,
    EIcon_arrow_left              = 0x45,
    EIcon_arrow_left_1            = 0x46,
    EIcon_arrow_right             = 0x47,
    EIcon_arrow_right_1           = 0x48,
    EIcon_arrow_up                = 0x49,
    EIcon_arrow_up_1              = 0x4A,
    EIcon_arrow_vertical          = 0x4B,
    EIcon_asterisk                = 0x4C,
    EIcon_backward                = 0x4D,
    EIcon_bar_chart               = 0x4E,
    EIcon_barcode                 = 0x4F,
    EIcon_beer                    = 0x50,
    EIcon_bell                    = 0x51,
    EIcon_bell_two                = 0x52,
    EIcon_bitbucket               = 0x53,
    EIcon_bitbucket_square        = 0x54,
    EIcon_bitcoin                 = 0x55,
    EIcon_bold                    = 0x56,
    EIcon_book                    = 0x57,
    EIcon_bookmark                = 0x58,
    EIcon_box_inbox               = 0x59,
    EIcon_briefcase_case          = 0x5A,
    EIcon_briefcase_case_two      = 0x30,
    EIcon_bug                     = 0x31,
    EIcon_building                = 0x32,
    EIcon_bullhorn                = 0x33,
    EIcon_bullseye                = 0x34,
    EIcon_calendar                = 0x35,
    EIcon_calendar_1              = 0x36,
    EIcon_call_phone              = 0x37,
    EIcon_call_phone_square       = 0x38,
    EIcon_camera                  = 0x39,
    EIcon_camera_retro            = 0x21,
    EIcon_caret_down              = 0x22,
    EIcon_caret_down_two          = 0x23,
    EIcon_caret_left              = 0x24,
    EIcon_caret_right             = 0x25,
    EIcon_caret_square_down       = 0x26,
    EIcon_caret_square_right      = 0x27,
    EIcon_caret_square_up         = 0x28,
    EIcon_caret_up                = 0x29,
    EIcon_caret_up_down           = 0x2A,
    EIcon_caret_up_two            = 0x2B,
    EIcon_certificate             = 0x2C,
    EIcon_chat_bubble             = 0x2D,
    EIcon_chat_bubble_two         = 0x2E,
    EIcon_check_mark              = 0x2F,
    EIcon_check_mark_2            = 0x3A,
    EIcon_check_mark_circle       = 0x3B,
    EIcon_check_mark_circle_two   = 0x3C,
    EIcon_check_square            = 0x3D,
    EIcon_chevron_down            = 0x3E,
    EIcon_chevron_down_circle     = 0x3F,
    EIcon_chevron_left            = 0x40,
    EIcon_chevron_right           = 0x5B,
    EIcon_chevron_up              = 0x5D,
    EIcon_chevron_up_circle       = 0x5E,
    EIcon_circle                  = 0x5F,
    EIcon_circle_line             = 0x60,
    EIcon_clipboard               = 0x7B,
    EIcon_clock                   = 0x7C,
    EIcon_close_delete            = 0x7D,
    EIcon_cloud                   = 0x7E,
    EIcon_cloud_download          = 0x5C,
    EIcon_cloud_upload            = 0xE000,
    EIcon_code                    = 0xE001,
    EIcon_code_fork               = 0xE002,
    EIcon_cog_gear                = 0xE003,
    EIcon_columns                 = 0xE004,
    EIcon_compass                 = 0xE005,
    EIcon_contrast                = 0xE006,
    EIcon_credit_card             = 0xE007,
    EIcon_crop                    = 0xE008,
    EIcon_crosshair_aim           = 0xE009,
    EIcon_css3                    = 0xE00A,
    EIcon_cup                     = 0xE00B,
    EIcon_cursor_move             = 0xE00C,
    EIcon_cursor_move_two         = 0xE00D,
    EIcon_cut_scissor             = 0xE00E,
    EIcon_cutlery                 = 0xE00F,
    EIcon_delete_circle           = 0xE010,
    EIcon_denied_block            = 0xE011,
    EIcon_dislike                 = 0xE012,
    EIcon_doctor                  = 0xE013,
    EIcon_document                = 0xE014,
    EIcon_dollar                  = 0xE015,
    EIcon_download                = 0xE016,
    EIcon_dribble                 = 0xE017,
    EIcon_dropbox                 = 0xE018,
    EIcon_earser                  = 0xE019,
    EIcon_edit_write              = 0xE01A,
    EIcon_eject                   = 0xE01B,
    EIcon_ellipsis                = 0xE01C,
    EIcon_ellipsis_2              = 0xE01D,
    EIcon_email_envelope          = 0xE01E,
    EIcon_euro                    = 0xE01F,
    EIcon_exchange                = 0xE020,
    EIcon_exclamation             = 0xE021,
    EIcon_exclamation_circle      = 0xE022,
    EIcon_exclamation_triangle    = 0xE023,
    EIcon_external_link           = 0xE024,
    EIcon_external_link_sqaure    = 0xE025,
    EIcon_eye                     = 0xE026,
    EIcon_eye_slash_close         = 0xE027,
    EIcon_facebook                = 0xE028,
    EIcon_facebook_square         = 0xE029,
    EIcon_fast_backward           = 0xE02A,
    EIcon_fast_forward            = 0xE02B,
    EIcon_female                  = 0xE02C,
    EIcon_fighter_jet             = 0xE02D,
    EIcon_file                    = 0xE02E,
    EIcon_file_document           = 0xE02F,
    EIcon_file_text               = 0xE030,
    EIcon_files                   = 0xE031,
    EIcon_filmstrip               = 0xE032,
    EIcon_filter                  = 0xE033,
    EIcon_fire                    = 0xE034,
    EIcon_fire_extinguisher       = 0xE035,
    EIcon_flag                    = 0xE036,
    EIcon_flag_1                  = 0xE037,
    EIcon_flag_goal               = 0xE038,
    EIcon_flash                   = 0xE039,
    EIcon_flickr                  = 0xE03A,
    EIcon_folder                  = 0xE03B,
    EIcon_folder2                 = 0xE03C,
    EIcon_folder3                 = 0xE03D,
    EIcon_folder_open             = 0xE03E,
    EIcon_font                    = 0xE03F,
    EIcon_fontawesome_webfont     = 0xE040,
    EIcon_forward                 = 0xE041,
    EIcon_foursquare              = 0xE042,
    EIcon_gamepad                 = 0xE043,
    EIcon_gears_setting           = 0xE044,
    EIcon_github                  = 0xE045,
    EIcon_github_square           = 0xE046,
    EIcon_gittip                  = 0xE047,
    EIcon_glass                   = 0xE048,
    EIcon_globe_world             = 0xE049,
    EIcon_google_plus             = 0xE04A,
    EIcon_google_plus_1           = 0xE04B,
    EIcon_group                   = 0xE04C,
    EIcon_hand_down               = 0xE04D,
    EIcon_hand_right              = 0xE04E,
    EIcon_hand_up                 = 0xE04F,
    EIcon_harddrive               = 0xE050,
    EIcon_headphone               = 0xE051,
    EIcon_heart                   = 0xE052,
    EIcon_heart_empty             = 0xE053,
    EIcon_home                    = 0xE054,
    EIcon_hospital                = 0xE055,
    EIcon_hospital_square         = 0xE056,
    EIcon_hospital_square_two     = 0xE057,
    EIcon_html5                   = 0xE058,
    EIcon_indent                  = 0xE059,
    EIcon_information             = 0xE05A,
    EIcon_information_circle      = 0xE05B,
    EIcon_instagram               = 0xE05C,
    EIcon_italic                  = 0xE05D,
    EIcon_key                     = 0xE05E,
    EIcon_keyboard                = 0xE05F,
    EIcon_laptop                  = 0xE060,
    EIcon_leaf                    = 0xE061,
    EIcon_left                    = 0xE062,
    EIcon_left_circle             = 0xE063,
    EIcon_legal                   = 0xE064,
    EIcon_lemon                   = 0xE065,
    EIcon_letter_mail             = 0xE066,
    EIcon_level_down              = 0xE067,
    EIcon_level_up                = 0xE068,
    EIcon_lightbulb               = 0xE069,
    EIcon_like                    = 0xE06A,
    EIcon_like_filled             = 0xE06B,
    EIcon_link                    = 0xE06C,
    EIcon_link_broken             = 0xE06D,
    EIcon_linkedin                = 0xE06E,
    EIcon_linkedin_square         = 0xE06F,
    EIcon_linux                   = 0xE070,
    EIcon_list                    = 0xE071,
    EIcon_list_2                  = 0xE072,
    EIcon_list_bullet             = 0xE073,
    EIcon_list_number             = 0xE074,
    EIcon_location_arrow          = 0xE075,
    EIcon_lock                    = 0xE076,
    EIcon_log_in                  = 0xE077,
    EIcon_log_out                 = 0xE078,
    EIcon_magic_wand              = 0xE079,
    EIcon_magnet                  = 0xE07A,
    EIcon_mail_forward            = 0xE07B,
    EIcon_male                    = 0xE07C,
    EIcon_maxcdn                  = 0xE07D,
    EIcon_mic                     = 0xE07E,
    EIcon_mic_no                  = 0xE07F,
    EIcon_minus                   = 0xE080,
    EIcon_minus_circle            = 0xE081,
    EIcon_minus_line              = 0xE082,
    EIcon_minus_square            = 0xE083,
    EIcon_minus_square_1          = 0xE084,
    EIcon_money_banknote          = 0xE085,
    EIcon_moon_sleep              = 0xE086,
    EIcon_music_note              = 0xE087,
    EIcon_outdent                 = 0xE088,
    EIcon_paper_clip              = 0xE089,
    EIcon_pause                   = 0xE08A,
    EIcon_pencil                  = 0xE08B,
    EIcon_pencil_square           = 0xE08C,
    EIcon_phone_mobile            = 0xE08D,
    EIcon_photo                   = 0xE08E,
    EIcon_pin_map                 = 0xE08F,
    EIcon_pin_map_2               = 0xE090,
    EIcon_pinterest               = 0xE091,
    EIcon_pinterest_square        = 0xE092,
    EIcon_plane_airport           = 0xE093,
    EIcon_play                    = 0xE094,
    EIcon_play_circle             = 0xE095,
    EIcon_plus                    = 0xE096,
    EIcon_plus_circle             = 0xE097,
    EIcon_plus_square             = 0xE098,
    EIcon_pound                   = 0xE099,
    EIcon_power_off               = 0xE09A,
    EIcon_present_gift            = 0xE09B,
    EIcon_prize_award             = 0xE09C,
    EIcon_ptint                   = 0xE09D,
    EIcon_puzzle                  = 0xE09E,
    EIcon_qrcode                  = 0xE09F,
    EIcon_question                = 0xE0A0,
    EIcon_question_1              = 0xE0A1,
    EIcon_quote_left              = 0xE0A2,
    EIcon_quote_right             = 0xE0A3,
    EIcon_random                  = 0xE0A4,
    EIcon_refresh                 = 0xE0A5,
    EIcon_remove                  = 0xE0A6,
    EIcon_renren                  = 0xE0A7,
    EIcon_repeat_redo             = 0xE0A8,
    EIcon_reply_all               = 0xE0A9,
    EIcon_reply_mail              = 0xE0AA,
    EIcon_resize_down             = 0xE0AB,
    EIcon_resize_expand           = 0xE0AC,
    EIcon_retweet                 = 0xE0AD,
    EIcon_right                   = 0xE0AE,
    EIcon_road                    = 0xE0AF,
    EIcon_rocket                  = 0xE0B0,
    EIcon_rss                     = 0xE0B1,
    EIcon_rss_two                 = 0xE0B2,
    EIcon_rupee                   = 0xE0B3,
    EIcon_save_disk               = 0xE0B4,
    EIcon_science_laboratory      = 0xE0B5,
    EIcon_screen_desktop          = 0xE0B6,
    EIcon_search_find             = 0xE0B7,
    EIcon_share_square            = 0xE0B8,
    EIcon_share_square_1          = 0xE0B9,
    EIcon_shield                  = 0xE0BA,
    EIcon_shopping_cart           = 0xE0BB,
    EIcon_signal                  = 0xE0BC,
    EIcon_sitemap                 = 0xE0BD,
    EIcon_skype                   = 0xE0BE,
    EIcon_smile                   = 0xE0BF,
    EIcon_smiley_frown            = 0xE0C0,
    EIcon_smiley_meh              = 0xE0C1,
    EIcon_sort_alpha              = 0xE0C2,
    EIcon_sort_alpha_two          = 0xE0C3,
    EIcon_sort_amount             = 0xE0C4,
    EIcon_sort_amount_two         = 0xE0C5,
    EIcon_sort_numeric            = 0xE0C6,
    EIcon_sort_numeric_two        = 0xE0C7,
    EIcon_spinner                 = 0xE0C8,
    EIcon_square                  = 0xE0C9,
    EIcon_square_line             = 0xE0CA,
    EIcon_stackoverflow           = 0xE0CB,
    EIcon_star                    = 0xE0CC,
    EIcon_star_half               = 0xE0CD,
    EIcon_star_half_1             = 0xE0CE,
    EIcon_star_two                = 0xE0CF,
    EIcon_step_backward           = 0xE0D0,
    EIcon_step_forward            = 0xE0D1,
    EIcon_stethoscope             = 0xE0D2,
    EIcon_stop                    = 0xE0D3,
    EIcon_strikethrough           = 0xE0D4,
    EIcon_subscript               = 0xE0D5,
    EIcon_sun                     = 0xE0D6,
    EIcon_superscript             = 0xE0D7,
    EIcon_table                   = 0xE0D8,
    EIcon_tablet                  = 0xE0D9,
    EIcon_tachometer              = 0xE0DA,
    EIcon_tag                     = 0xE0DB,
    EIcon_tag_2                   = 0xE0DC,
    EIcon_tags                    = 0xE0DD,
    EIcon_talk_chat               = 0xE0DE,
    EIcon_talk_chat_2             = 0xE0DF,
    EIcon_tasks                   = 0xE0E0,
    EIcon_terminal                = 0xE0E1,
    EIcon_text_height             = 0xE0E2,
    EIcon_text_width              = 0xE0E3,
    EIcon_thumbnails              = 0xE0E4,
    EIcon_thumbnails_large        = 0xE0E5,
    EIcon_ticket                  = 0xE0E6,
    EIcon_tint                    = 0xE0E7,
    EIcon_trash_bin               = 0xE0E8,
    EIcon_trello                  = 0xE0E9,
    EIcon_truck                   = 0xE0EA,
    EIcon_tumblr                  = 0xE0EB,
    EIcon_tumblr_square           = 0xE0EC,
    EIcon_twitter                 = 0xE0ED,
    EIcon_twitter_square          = 0xE0EE,
    EIcon_umbrella                = 0xE0EF,
    EIcon_underline               = 0xE0F0,
    EIcon_undo                    = 0xE0F1,
    EIcon_unlike                  = 0xE0F2,
    EIcon_unlock                  = 0xE0F3,
    EIcon_unlock_2                = 0xE0F4,
    EIcon_upload                  = 0xE0F5,
    EIcon_user                    = 0xE0F6,
    EIcon_video_camera            = 0xE0F7,
    EIcon_vk                      = 0xE0F8,
    EIcon_volume_down             = 0xE0F9,
    EIcon_volume_down_1           = 0xE0FA,
    EIcon_volume_up               = 0xE0FB,
    EIcon_weibo                   = 0xE0FC,
    EIcon_window_list             = 0xE0FD,
    EIcon_windows                 = 0xE0FE,
    EIcon_won                     = 0xE0FF,
    EIcon_wrench                  = 0xE100,
    EIcon_xing                    = 0xE101,
    EIcon_xing_square             = 0xE102,
    EIcon_yen                     = 0xE103,
    EIcon_youtube                 = 0xE104,
    EIcon_youtube_play            = 0xE105,
    EIcon_youtube_square          = 0xE106,
    EIcon_yuan                    = 0xE107,
    EIcon_zoom_in                 = 0xE108,
    EIcon_zoom_out                = 0xE109,
};

class cGcNGuiLayer;

class cGcNGuiElement : public ITkNGuiDraggable
{
  public:
    enum eLayoutChangeEvent
    {
        ELayoutChange_Nothing,
        ELayoutChange_PositionMode,
        ELayoutChange_WidthMode,
        ELayoutChange_HeightMode,
        ELayoutChange_ConstrainMode,
        ELayoutChange_Size,
        ELayoutChange_Width,
        ELayoutChange_Height,
        ELayoutChange_Value,
        ELayoutChange_ColourPreset,
    };

    struct sGcNGuiElementAnimSettings
    {
        int8_t mbRequestAnimActivate : 1;
        int8_t mbRequestAnimReset : 1;
    };

    cTkBBox2d mContentBBox;
    cTkVector2 mvParallaxOffset;
    cTkNGuiTypeUndoable<cGcNGuiLayoutData> *mpUndoMoveEvent;
    cTkNGuiTypeUndoable<cGcNGuiLayoutData> *mpUndoResizeEvent;
    cTkNGuiTypeUndoable<cGcNGuiLayoutData> *mpUndoLayoutEvent;
    cGcNGuiLayer *mpParent;
    cGcNGuiElementData *mpElementData;
    eNGuiInputType meInputThisFrame;
    cGcNGuiElement::eLayoutChangeEvent meLayoutChangeEvent;
    eNGuiAnimationEvent meRequestAnim;
    cGcNGuiElement::sGcNGuiElementAnimSettings mAnim;
    bool mbSelectedToEdit;

    virtual void Render();
    virtual int GetType() { return NULL; }
    virtual ~cGcNGuiElement();
    virtual void EditElement();
    virtual void EditPresets(cGcNGuiPreset *);
    virtual void RenderUIEditorToolbar(cGcNGuiPreset *);
    virtual bool SelectableInEditor();
    virtual void SetNeedsUpdate();
    virtual void Deselect();
    virtual bool IsSelected();
    virtual void Resized();
    virtual void AttachMetadata(cTkClassPointer *);
    virtual void DetachMetadata(cTkClassPointer *);
    virtual bool IsLayer();
    virtual eNGuiEditorIcons GetSceneTreeIcon();
    virtual void GetSceneTreeText(cTkFixedString<128, char> *);
    virtual void RenderAdditionalOverlayIcons(const cTkVector2 *, const cTkVector2 *);
    virtual void RenderTreeControls();
};

SKYSCRAPER_END