#pragma once
#include <metadata/metadata_common.h>
#include <metadata/reality/gcdiscoveryworth.meta.h>
#include <metadata/reality/gcsubstancesecondarylookup.meta.h>
#include <metadata/reality/gcsubstancesecondarybiome.meta.h>
#include <metadata/tkrawid.meta.h>
#include <metadata/reality/gcalienpuzzletableindex.meta.h>
#include <metadata/animation/tkcurvetype.meta.h>
#include <metadata/simulation/projectiles/gcdamagemultiplierlookup.meta.h>
#include <metadata/reality/gcfreightercargooption.meta.h>
#include <metadata/simulation/weapons/gcshipweapondata.meta.h>
#include <metadata/simulation/weapons/gcplayerweapondata.meta.h>
#include <metadata/tkidarray.meta.h>
#include <metadata/reality/gcnumberedtextlist.meta.h>
#include <metadata/reality/gcrealityicontable.meta.h>
#include <metadata/tktextureresource.meta.h>
#include <metadata/reality/gcstats.meta.h>
#include <metadata/reality/gctechlist.meta.h>
#include <metadata/reality/gctradesettings.meta.h>
#include <metadata/gamestate/gcinventorylayout.meta.h>
#include <metadata/gameplay/gcfiendcrimespawntable.meta.h>
#include <metadata/simulation/environment/wfcbuildings/gcidpair.meta.h>

class cGcRealityManagerData
{
    static unsigned long long muNameHash = 0x5930542B7B565329;
    static unsigned long long muTemplateHash = 0xD01E8D3C598026F4;

    unsigned short muiHomeRealityIteration;
    unsigned short muiRealityIteration;
    cTkFixedArray<cGcDiscoveryWorth> maDiscoveryWorth;
    cTkFixedArray<float> maCreatureDiscoverySizeMultiplier;
    cTkDynamicArray<cGcSubstanceSecondaryLookup> maSubstanceSecondaryLookups;
    cGcSubstanceSecondaryBiome SubstanceSecondaryBiome;
    cTkFixedString<128,char> macTechnologyTable;
    cTkFixedString<128,char> macSubstanceTable;
    cTkFixedString<128,char> macProductTable;
    cTkFixedString<128,char> macProceduralProductTable;
    cTkFixedString<128,char> macProceduralTechnologyTable;
    cTkFixedString<128,char> macLegacyItemConversionTable;
    cTkDynamicArray<cTkRawID> maLegacyRepairTable;
    cTkFixedString<128,char> macConsumableItemTable;
    cTkFixedString<128,char> macRecipeTable;
    cTkFixedString<128,char> macStoriesTable;
    cTkFixedString<128,char> macDialogClearanceTable;
    cTkFixedString<128,char> macAlienWordsTable;
    cTkDynamicArray<cTkFixedString<128,char>> maAlienPuzzleTables;
    cTkFixedArray<bool> maLoopInteractionPuzzles;
    cTkFixedArray<cGcAlienPuzzleTableIndex> maInteractionPuzzlesIndexTypes;
    cTkFixedArray<cTkCurveType> maWeightingCurves;
    cTkDynamicArray<cGcDamageMultiplierLookup> maDamageMultiplierTable;
    cTkFixedString<128,char> macRewardTable;
    cTkFixedString<128,char> macDiscoveryRewardTable;
    cTkFixedString<128,char> macInventoryTable;
    cTkFixedString<128,char> macDamageTable;
    cTkFixedString<128,char> macPurchaseableBuildingBlueprintsTable;
    cTkFixedString<128,char> macPurchaseableSpecialsTable;
    cTkFixedString<128,char> macUnlockableSeasonRewardsTable;
    cTkFixedString<128,char> macUnlockableTwitchRewardsTable;
    cTkFixedString<128,char> macUnlockablePlatformRewardsTable;
    cTkFixedString<128,char> macCostTable;
    cTkFixedString<128,char> macTradingCostTable;
    cTkFixedString<128,char> macTradingClassDataTable;
    cTkFixedString<128,char> macMaintenanceGroupsTable;
    cTkFixedString<128,char> macUnlockableItemTrees;
    cTkFixedString<128,char> macSettlementPerksTable;
    cTkFixedString<128,char> macPlayerWeaponPropertiesTable;
    cTkFixedString<128,char> macCombatEffectsTable;
    cTkFixedString<128,char> macTechBoxTable;
    cTkDynamicArray<cGcFreighterCargoOption> maFreighterCargoOptions;
    cTkFixedArray<cGcShipWeaponData> maShipWeapons;
    cTkFixedArray<cGcPlayerWeaponData> maPlayerWeapons;
    cTkFixedArray<cTkIdArray> maDefaultVehicleLoadout;
    cTkFixedArray<TkID<128>> maFactionStandingIDs;
    cTkFixedArray<TkID<256>> maFactionNames;
    cTkFixedArray<cGcNumberedTextList> maFactionClients;
    cTkFixedArray<cGcNumberedTextList> maMissionNameFormats;
    cTkFixedArray<cGcNumberedTextList> maMissionNameAdjectives;
    cTkFixedArray<cGcNumberedTextList> maMissionNameNouns;
    cTkFixedArray<cTkIdArray> maMissionBoardRewardOptions;
    cTkFixedArray<float> maWeightedTextWeights;
    cGcRealityIconTable Icons;
    cTkFixedArray<cTkColour> maHazardColours;
    cTkFixedArray<cTkColour> maRarityColours;
    cTkFixedArray<cTkColour> maSubstanceCategoryColours;
    cTkFixedArray<cTkTextureResource> maSubstanceChargeIcons;
    cTkFixedArray<cTkTextureResource> maStatCategoryIcons;
    cTkFixedArray<cTkTextureResource> maStatTechPackageIcons;
    cTkFixedArray<cGcStats> maStats;
    cGcTechList StationTechShops;
    cTkFixedArray<cGcTechList> maPlanetTechShops;
    cGcTradeSettings TradeSettings;
    cTkDynamicArray<TkID<128>> maPirateStationExtraProds;
    cGcInventoryLayout SuitStartingSlotLayout;
    cGcInventoryLayout SuitTechOnlyStartingSlotLayout;
    cGcInventoryLayout SuitCargoStartingSlotLayout;
    cGcInventoryLayout ShipStartingLayout;
    cGcInventoryLayout ShipTechOnlyStartingLayout;
    cGcInventoryLayout ShipCargoOnlyStartingLayout;
    cTkDynamicArray<int> maSuitUpgradePrices;
    cTkDynamicArray<int> maSuitTechOnlyUpgradePrices;
    cTkDynamicArray<int> maSuitCargoUpgradePrices;
    cTkDynamicArray<TkID<128>> maNeverSellableItems;
    cTkDynamicArray<TkID<128>> maNeverOfferedForSale;
    cTkFixedArray<float> maNormalisedPriceLimits;
    cTkDynamicArray<cGcFiendCrimeSpawnTable> maFiendCrimeSpawnTable;
    cTkDynamicArray<cGcIDPair> maFreighterBaseItemPairs;
    cTkFixedArray<cTkFixedString<128,char>> maCatalogues;
}
