#pragma once
#include <metadata/metadata_common.h>

class cGcCameraFollowSettings
{
    static unsigned long long muNameHash = 0x200FDA306DC86654;
    static unsigned long long muTemplateHash = 0xDF33D9C6EF3F5AF1;

    TkID<128> mName;
    float mfMinSpeed;
    float mfSpeedRange;
    float mfOffsetX;
    float mfOffsetY;
    float mfOffsetYAlt;
    float mfOffsetYSlopeExtra;
    float mfOffsetZFlat;
    float mfBackMinDistance;
    float mfBackMaxDistance;
    float mfBackSlopeAdjust;
    float mfBackSlopeRotationAdjust;
    float mfUpMinDistance;
    float mfUpMaxDistance;
    float mfUpSlopeAdjust;
    float mfLeftMinDistance;
    float mfLeftMaxDistance;
    float mfOffsetYExtraMaxDistance;
    float mfPanNear;
    float mfPanFar;
    float mfUpGamma;
    float mfHorizRotationAngleMaxPerFrame;
    float mfVertRotationSpeed;
    float mfVertRotationMin;
    float mfVertRotationMax;
    float mfVertRotationOffset;
    float mfVertRotationOffsetMinAngle;
    float mfVertRotationOffsetMaxAngle;
    bool mbVertStartLookingDown;
    float mfDistSpeed;
    float mfDistSpeedOutsideMainRange;
    float mfDistStiffness;
    float mfSpringSpeed;
    bool mbLockToObjectOnIdle;
    float mfCenterStartTime;
    float mfCenterBlendTime;
    float mfCenterMaxSpring;
    float mfCenterMaxSpeed;
    float mfVelocityAnticipate;
    float mfVelocityAnticipateSpringSpeed;
    float mfVertMaxSpring;
    float mfCenterStartSpeed;
    float mfLookStickLimitAngle;
    bool mbEnableCollisionDetection;
    int miNumLRProbes;
    float mfLRProbesRange;
    float mfLRProbesRadius;
    int miNumUDProbes;
    float mfUDProbesRange;
    float mfProbeCenterX;
    float mfProbeCenterY;
    float mfPushForwardDropoffLR;
    float mfPushForwardDropoffUD;
    float mfAvoidCollisionLRSpeed;
    float mfAvoidCollisionUDSpeed;
    float mfAvoidCollisionPushSpeed;
    bool mbAvoidCollisionUDUseStickDelay;
    bool mbAvoidCollisionLRUseStickDelay;
    bool mbUseSpeedBasedSpring;
    bool mbUseCustomBlendTime;
    float mfCustomBlendTime;
}
