/**
 * @file exports.h
 * @author VITALISED & Contributors
 * @since 2023-12-05
 * 
 * Copyright (C) 2023  VITALISED & Contributors
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// clang-format off

#pragma comment(linker,"/export:sceFiosArchiveGetDecompressorThreadCount=libSceFios2_orig.sceFiosArchiveGetDecompressorThreadCount,@1")
#pragma comment(linker,"/export:sceFiosArchiveGetMountBufferSize=libSceFios2_orig.sceFiosArchiveGetMountBufferSize,@2")
#pragma comment(linker,"/export:sceFiosArchiveGetMountBufferSizeSync=libSceFios2_orig.sceFiosArchiveGetMountBufferSizeSync,@3")
#pragma comment(linker,"/export:sceFiosArchiveMount=libSceFios2_orig.sceFiosArchiveMount,@4")
#pragma comment(linker,"/export:sceFiosArchiveMountSync=libSceFios2_orig.sceFiosArchiveMountSync,@5")
#pragma comment(linker,"/export:sceFiosArchiveMountWithOrder=libSceFios2_orig.sceFiosArchiveMountWithOrder,@6")
#pragma comment(linker,"/export:sceFiosArchiveMountWithOrderSync=libSceFios2_orig.sceFiosArchiveMountWithOrderSync,@7")
#pragma comment(linker,"/export:sceFiosArchiveSetDecompressorThreadCount=libSceFios2_orig.sceFiosArchiveSetDecompressorThreadCount,@8")
#pragma comment(linker,"/export:sceFiosArchiveUnmount=libSceFios2_orig.sceFiosArchiveUnmount,@9")
#pragma comment(linker,"/export:sceFiosArchiveUnmountSync=libSceFios2_orig.sceFiosArchiveUnmountSync,@10")
#pragma comment(linker,"/export:sceFiosCacheContainsFileRangeSync=libSceFios2_orig.sceFiosCacheContainsFileRangeSync,@11")
#pragma comment(linker,"/export:sceFiosCacheContainsFileSync=libSceFios2_orig.sceFiosCacheContainsFileSync,@12")
#pragma comment(linker,"/export:sceFiosCacheFlushFileRangeSync=libSceFios2_orig.sceFiosCacheFlushFileRangeSync,@13")
#pragma comment(linker,"/export:sceFiosCacheFlushFileSync=libSceFios2_orig.sceFiosCacheFlushFileSync,@14")
#pragma comment(linker,"/export:sceFiosCacheFlushSync=libSceFios2_orig.sceFiosCacheFlushSync,@15")
#pragma comment(linker,"/export:sceFiosCachePrefetchFH=libSceFios2_orig.sceFiosCachePrefetchFH,@16")
#pragma comment(linker,"/export:sceFiosCachePrefetchFHRange=libSceFios2_orig.sceFiosCachePrefetchFHRange,@17")
#pragma comment(linker,"/export:sceFiosCachePrefetchFHRangeSync=libSceFios2_orig.sceFiosCachePrefetchFHRangeSync,@18")
#pragma comment(linker,"/export:sceFiosCachePrefetchFHSync=libSceFios2_orig.sceFiosCachePrefetchFHSync,@19")
#pragma comment(linker,"/export:sceFiosCachePrefetchFile=libSceFios2_orig.sceFiosCachePrefetchFile,@20")
#pragma comment(linker,"/export:sceFiosCachePrefetchFileRange=libSceFios2_orig.sceFiosCachePrefetchFileRange,@21")
#pragma comment(linker,"/export:sceFiosCachePrefetchFileRangeSync=libSceFios2_orig.sceFiosCachePrefetchFileRangeSync,@22")
#pragma comment(linker,"/export:sceFiosCachePrefetchFileSync=libSceFios2_orig.sceFiosCachePrefetchFileSync,@23")
#pragma comment(linker,"/export:sceFiosCancelAllOps=libSceFios2_orig.sceFiosCancelAllOps,@24")
#pragma comment(linker,"/export:sceFiosClearTimeStamps=libSceFios2_orig.sceFiosClearTimeStamps,@25")
#pragma comment(linker,"/export:sceFiosCloseAllFiles=libSceFios2_orig.sceFiosCloseAllFiles,@26")
#pragma comment(linker,"/export:sceFiosDHClose=libSceFios2_orig.sceFiosDHClose,@27")
#pragma comment(linker,"/export:sceFiosDHCloseSync=libSceFios2_orig.sceFiosDHCloseSync,@28")
#pragma comment(linker,"/export:sceFiosDHGetPath=libSceFios2_orig.sceFiosDHGetPath,@29")
#pragma comment(linker,"/export:sceFiosDHOpen=libSceFios2_orig.sceFiosDHOpen,@30")
#pragma comment(linker,"/export:sceFiosDHOpenSync=libSceFios2_orig.sceFiosDHOpenSync,@31")
#pragma comment(linker,"/export:sceFiosDHRead=libSceFios2_orig.sceFiosDHRead,@32")
#pragma comment(linker,"/export:sceFiosDHReadSync=libSceFios2_orig.sceFiosDHReadSync,@33")
#pragma comment(linker,"/export:sceFiosDLLInitialize=libSceFios2_orig.sceFiosDLLInitialize,@34")
#pragma comment(linker,"/export:sceFiosDLLTerminate=libSceFios2_orig.sceFiosDLLTerminate,@35")
#pragma comment(linker,"/export:sceFiosDateFromComponents=libSceFios2_orig.sceFiosDateFromComponents,@36")
#pragma comment(linker,"/export:sceFiosDateFromFILETIME=libSceFios2_orig.sceFiosDateFromFILETIME,@37")
#pragma comment(linker,"/export:sceFiosDateGetCurrent=libSceFios2_orig.sceFiosDateGetCurrent,@38")
#pragma comment(linker,"/export:sceFiosDateToComponents=libSceFios2_orig.sceFiosDateToComponents,@39")
#pragma comment(linker,"/export:sceFiosDeallocatePassthruFH=libSceFios2_orig.sceFiosDeallocatePassthruFH,@40")
#pragma comment(linker,"/export:sceFiosDebugDumpDH=libSceFios2_orig.sceFiosDebugDumpDH,@41")
#pragma comment(linker,"/export:sceFiosDebugDumpDate=libSceFios2_orig.sceFiosDebugDumpDate,@42")
#pragma comment(linker,"/export:sceFiosDebugDumpError=libSceFios2_orig.sceFiosDebugDumpError,@43")
#pragma comment(linker,"/export:sceFiosDebugDumpFH=libSceFios2_orig.sceFiosDebugDumpFH,@44")
#pragma comment(linker,"/export:sceFiosDebugDumpIOSchedulerQueues=libSceFios2_orig.sceFiosDebugDumpIOSchedulerQueues,@45")
#pragma comment(linker,"/export:sceFiosDebugDumpOp=libSceFios2_orig.sceFiosDebugDumpOp,@46")
#pragma comment(linker,"/export:sceFiosDebugSetProfileCallback=libSceFios2_orig.sceFiosDebugSetProfileCallback,@47")
#pragma comment(linker,"/export:sceFiosDebugSetTraceMask=libSceFios2_orig.sceFiosDebugSetTraceMask,@48")
#pragma comment(linker,"/export:sceFiosDebugStatisticsGet=libSceFios2_orig.sceFiosDebugStatisticsGet,@49")
#pragma comment(linker,"/export:sceFiosDebugStatisticsPrint=libSceFios2_orig.sceFiosDebugStatisticsPrint,@50")
#pragma comment(linker,"/export:sceFiosDebugStatisticsReset=libSceFios2_orig.sceFiosDebugStatisticsReset,@51")
#pragma comment(linker,"/export:sceFiosDelete=libSceFios2_orig.sceFiosDelete,@52")
#pragma comment(linker,"/export:sceFiosDeleteSync=libSceFios2_orig.sceFiosDeleteSync,@53")
#pragma comment(linker,"/export:sceFiosDirectoryCreate=libSceFios2_orig.sceFiosDirectoryCreate,@54")
#pragma comment(linker,"/export:sceFiosDirectoryCreateSync=libSceFios2_orig.sceFiosDirectoryCreateSync,@55")
#pragma comment(linker,"/export:sceFiosDirectoryCreateWithMode=libSceFios2_orig.sceFiosDirectoryCreateWithMode,@56")
#pragma comment(linker,"/export:sceFiosDirectoryCreateWithModeSync=libSceFios2_orig.sceFiosDirectoryCreateWithModeSync,@57")
#pragma comment(linker,"/export:sceFiosDirectoryDelete=libSceFios2_orig.sceFiosDirectoryDelete,@58")
#pragma comment(linker,"/export:sceFiosDirectoryDeleteSync=libSceFios2_orig.sceFiosDirectoryDeleteSync,@59")
#pragma comment(linker,"/export:sceFiosDirectoryExists=libSceFios2_orig.sceFiosDirectoryExists,@60")
#pragma comment(linker,"/export:sceFiosDirectoryExistsSync=libSceFios2_orig.sceFiosDirectoryExistsSync,@61")
#pragma comment(linker,"/export:sceFiosExists=libSceFios2_orig.sceFiosExists,@62")
#pragma comment(linker,"/export:sceFiosExistsSync=libSceFios2_orig.sceFiosExistsSync,@63")
#pragma comment(linker,"/export:sceFiosFHClose=libSceFios2_orig.sceFiosFHClose,@64")
#pragma comment(linker,"/export:sceFiosFHCloseSync=libSceFios2_orig.sceFiosFHCloseSync,@65")
#pragma comment(linker,"/export:sceFiosFHGetOpenParams=libSceFios2_orig.sceFiosFHGetOpenParams,@66")
#pragma comment(linker,"/export:sceFiosFHGetPath=libSceFios2_orig.sceFiosFHGetPath,@67")
#pragma comment(linker,"/export:sceFiosFHGetSize=libSceFios2_orig.sceFiosFHGetSize,@68")
#pragma comment(linker,"/export:sceFiosFHOpen=libSceFios2_orig.sceFiosFHOpen,@69")
#pragma comment(linker,"/export:sceFiosFHOpenSync=libSceFios2_orig.sceFiosFHOpenSync,@70")
#pragma comment(linker,"/export:sceFiosFHOpenWithMode=libSceFios2_orig.sceFiosFHOpenWithMode,@71")
#pragma comment(linker,"/export:sceFiosFHOpenWithModeSync=libSceFios2_orig.sceFiosFHOpenWithModeSync,@72")
#pragma comment(linker,"/export:sceFiosFHPread=libSceFios2_orig.sceFiosFHPread,@73")
#pragma comment(linker,"/export:sceFiosFHPreadSync=libSceFios2_orig.sceFiosFHPreadSync,@74")
#pragma comment(linker,"/export:sceFiosFHPreadv=libSceFios2_orig.sceFiosFHPreadv,@75")
#pragma comment(linker,"/export:sceFiosFHPreadvSync=libSceFios2_orig.sceFiosFHPreadvSync,@76")
#pragma comment(linker,"/export:sceFiosFHPwrite=libSceFios2_orig.sceFiosFHPwrite,@77")
#pragma comment(linker,"/export:sceFiosFHPwriteSync=libSceFios2_orig.sceFiosFHPwriteSync,@78")
#pragma comment(linker,"/export:sceFiosFHPwritev=libSceFios2_orig.sceFiosFHPwritev,@79")
#pragma comment(linker,"/export:sceFiosFHPwritevSync=libSceFios2_orig.sceFiosFHPwritevSync,@80")
#pragma comment(linker,"/export:sceFiosFHRead=libSceFios2_orig.sceFiosFHRead,@81")
#pragma comment(linker,"/export:sceFiosFHReadSync=libSceFios2_orig.sceFiosFHReadSync,@82")
#pragma comment(linker,"/export:sceFiosFHReadv=libSceFios2_orig.sceFiosFHReadv,@83")
#pragma comment(linker,"/export:sceFiosFHReadvSync=libSceFios2_orig.sceFiosFHReadvSync,@84")
#pragma comment(linker,"/export:sceFiosFHSeek=libSceFios2_orig.sceFiosFHSeek,@85")
#pragma comment(linker,"/export:sceFiosFHStat=libSceFios2_orig.sceFiosFHStat,@86")
#pragma comment(linker,"/export:sceFiosFHStatSync=libSceFios2_orig.sceFiosFHStatSync,@87")
#pragma comment(linker,"/export:sceFiosFHSync=libSceFios2_orig.sceFiosFHSync,@88")
#pragma comment(linker,"/export:sceFiosFHSyncSync=libSceFios2_orig.sceFiosFHSyncSync,@89")
#pragma comment(linker,"/export:sceFiosFHTell=libSceFios2_orig.sceFiosFHTell,@90")
#pragma comment(linker,"/export:sceFiosFHToFileno=libSceFios2_orig.sceFiosFHToFileno,@91")
#pragma comment(linker,"/export:sceFiosFHTruncate=libSceFios2_orig.sceFiosFHTruncate,@92")
#pragma comment(linker,"/export:sceFiosFHTruncateSync=libSceFios2_orig.sceFiosFHTruncateSync,@93")
#pragma comment(linker,"/export:sceFiosFHWrite=libSceFios2_orig.sceFiosFHWrite,@94")
#pragma comment(linker,"/export:sceFiosFHWriteSync=libSceFios2_orig.sceFiosFHWriteSync,@95")
#pragma comment(linker,"/export:sceFiosFHWritev=libSceFios2_orig.sceFiosFHWritev,@96")
#pragma comment(linker,"/export:sceFiosFHWritevSync=libSceFios2_orig.sceFiosFHWritevSync,@97")
#pragma comment(linker,"/export:sceFiosFileDelete=libSceFios2_orig.sceFiosFileDelete,@98")
#pragma comment(linker,"/export:sceFiosFileDeleteSync=libSceFios2_orig.sceFiosFileDeleteSync,@99")
#pragma comment(linker,"/export:sceFiosFileExists=libSceFios2_orig.sceFiosFileExists,@100")
#pragma comment(linker,"/export:sceFiosFileExistsSync=libSceFios2_orig.sceFiosFileExistsSync,@101")
#pragma comment(linker,"/export:sceFiosFileGetSize=libSceFios2_orig.sceFiosFileGetSize,@102")
#pragma comment(linker,"/export:sceFiosFileGetSizeSync=libSceFios2_orig.sceFiosFileGetSizeSync,@103")
#pragma comment(linker,"/export:sceFiosFileRead=libSceFios2_orig.sceFiosFileRead,@104")
#pragma comment(linker,"/export:sceFiosFileReadSync=libSceFios2_orig.sceFiosFileReadSync,@105")
#pragma comment(linker,"/export:sceFiosFileTruncate=libSceFios2_orig.sceFiosFileTruncate,@106")
#pragma comment(linker,"/export:sceFiosFileTruncateSync=libSceFios2_orig.sceFiosFileTruncateSync,@107")
#pragma comment(linker,"/export:sceFiosFileWrite=libSceFios2_orig.sceFiosFileWrite,@108")
#pragma comment(linker,"/export:sceFiosFileWriteSync=libSceFios2_orig.sceFiosFileWriteSync,@109")
#pragma comment(linker,"/export:sceFiosFilenoToFH=libSceFios2_orig.sceFiosFilenoToFH,@110")
#pragma comment(linker,"/export:sceFiosGetAllDHs=libSceFios2_orig.sceFiosGetAllDHs,@111")
#pragma comment(linker,"/export:sceFiosGetAllFHs=libSceFios2_orig.sceFiosGetAllFHs,@112")
#pragma comment(linker,"/export:sceFiosGetAllOps=libSceFios2_orig.sceFiosGetAllOps,@113")
#pragma comment(linker,"/export:sceFiosGetDefaultOpAttr=libSceFios2_orig.sceFiosGetDefaultOpAttr,@114")
#pragma comment(linker,"/export:sceFiosGetGlobalDefaultOpAttr=libSceFios2_orig.sceFiosGetGlobalDefaultOpAttr,@115")
#pragma comment(linker,"/export:sceFiosGetSuspendCount=libSceFios2_orig.sceFiosGetSuspendCount,@116")
#pragma comment(linker,"/export:sceFiosGetThreadDefaultOpAttr=libSceFios2_orig.sceFiosGetThreadDefaultOpAttr,@117")
#pragma comment(linker,"/export:sceFiosIOFilterAdd=libSceFios2_orig.sceFiosIOFilterAdd,@118")
#pragma comment(linker,"/export:sceFiosIOFilterCache=libSceFios2_orig.sceFiosIOFilterCache,@119")
#pragma comment(linker,"/export:sceFiosIOFilterGetInfo=libSceFios2_orig.sceFiosIOFilterGetInfo,@120")
#pragma comment(linker,"/export:sceFiosIOFilterPsarcDearchiver=libSceFios2_orig.sceFiosIOFilterPsarcDearchiver,@121")
#pragma comment(linker,"/export:sceFiosIOFilterRemove=libSceFios2_orig.sceFiosIOFilterRemove,@122")
#pragma comment(linker,"/export:sceFiosInitialize=libSceFios2_orig.sceFiosInitialize,@123")
#pragma comment(linker,"/export:sceFiosIsIdle=libSceFios2_orig.sceFiosIsIdle,@124")
#pragma comment(linker,"/export:sceFiosIsInitialized=libSceFios2_orig.sceFiosIsInitialized,@125")
#pragma comment(linker,"/export:sceFiosIsSuspended=libSceFios2_orig.sceFiosIsSuspended,@126")
#pragma comment(linker,"/export:sceFiosIsValidHandle=libSceFios2_orig.sceFiosIsValidHandle,@127")
#pragma comment(linker,"/export:sceFiosOpCancel=libSceFios2_orig.sceFiosOpCancel,@128")
#pragma comment(linker,"/export:sceFiosOpDelete=libSceFios2_orig.sceFiosOpDelete,@129")
#pragma comment(linker,"/export:sceFiosOpGetActualCount=libSceFios2_orig.sceFiosOpGetActualCount,@130")
#pragma comment(linker,"/export:sceFiosOpGetAttr=libSceFios2_orig.sceFiosOpGetAttr,@131")
#pragma comment(linker,"/export:sceFiosOpGetBuffer=libSceFios2_orig.sceFiosOpGetBuffer,@132")
#pragma comment(linker,"/export:sceFiosOpGetError=libSceFios2_orig.sceFiosOpGetError,@133")
#pragma comment(linker,"/export:sceFiosOpGetOffset=libSceFios2_orig.sceFiosOpGetOffset,@134")
#pragma comment(linker,"/export:sceFiosOpGetPath=libSceFios2_orig.sceFiosOpGetPath,@135")
#pragma comment(linker,"/export:sceFiosOpGetRequestCount=libSceFios2_orig.sceFiosOpGetRequestCount,@136")
#pragma comment(linker,"/export:sceFiosOpIsCancelled=libSceFios2_orig.sceFiosOpIsCancelled,@137")
#pragma comment(linker,"/export:sceFiosOpIsDone=libSceFios2_orig.sceFiosOpIsDone,@138")
#pragma comment(linker,"/export:sceFiosOpReschedule=libSceFios2_orig.sceFiosOpReschedule,@139")
#pragma comment(linker,"/export:sceFiosOpRescheduleWithPriority=libSceFios2_orig.sceFiosOpRescheduleWithPriority,@140")
#pragma comment(linker,"/export:sceFiosOpSetBuffer=libSceFios2_orig.sceFiosOpSetBuffer,@141")
#pragma comment(linker,"/export:sceFiosOpSyncWait=libSceFios2_orig.sceFiosOpSyncWait,@142")
#pragma comment(linker,"/export:sceFiosOpSyncWaitForIO=libSceFios2_orig.sceFiosOpSyncWaitForIO,@143")
#pragma comment(linker,"/export:sceFiosOpWait=libSceFios2_orig.sceFiosOpWait,@144")
#pragma comment(linker,"/export:sceFiosOpWaitUntil=libSceFios2_orig.sceFiosOpWaitUntil,@145")
#pragma comment(linker,"/export:sceFiosOverlayAdd=libSceFios2_orig.sceFiosOverlayAdd,@146")
#pragma comment(linker,"/export:sceFiosOverlayGetInfo=libSceFios2_orig.sceFiosOverlayGetInfo,@147")
#pragma comment(linker,"/export:sceFiosOverlayGetList=libSceFios2_orig.sceFiosOverlayGetList,@148")
#pragma comment(linker,"/export:sceFiosOverlayModify=libSceFios2_orig.sceFiosOverlayModify,@149")
#pragma comment(linker,"/export:sceFiosOverlayRemove=libSceFios2_orig.sceFiosOverlayRemove,@150")
#pragma comment(linker,"/export:sceFiosOverlayResolveSync=libSceFios2_orig.sceFiosOverlayResolveSync,@151")
#pragma comment(linker,"/export:sceFiosPathNormalize=libSceFios2_orig.sceFiosPathNormalize,@152")
#pragma comment(linker,"/export:sceFiosPathcmp=libSceFios2_orig.sceFiosPathcmp,@153")
#pragma comment(linker,"/export:sceFiosPathncmp=libSceFios2_orig.sceFiosPathncmp,@154")
#pragma comment(linker,"/export:sceFiosPrintTimeStamps=libSceFios2_orig.sceFiosPrintTimeStamps,@155")
#pragma comment(linker,"/export:sceFiosPrintf=libSceFios2_orig.sceFiosPrintf,@156")
#pragma comment(linker,"/export:sceFiosRename=libSceFios2_orig.sceFiosRename,@157")
#pragma comment(linker,"/export:sceFiosRenameSync=libSceFios2_orig.sceFiosRenameSync,@158")
#pragma comment(linker,"/export:sceFiosResolve=libSceFios2_orig.sceFiosResolve,@159")
#pragma comment(linker,"/export:sceFiosResolveSync=libSceFios2_orig.sceFiosResolveSync,@160")
#pragma comment(linker,"/export:sceFiosResume=libSceFios2_orig.sceFiosResume,@161")
#pragma comment(linker,"/export:sceFiosSaveTimeStamp=libSceFios2_orig.sceFiosSaveTimeStamp,@162")
#pragma comment(linker,"/export:sceFiosSetGlobalDefaultOpAttr=libSceFios2_orig.sceFiosSetGlobalDefaultOpAttr,@163")
#pragma comment(linker,"/export:sceFiosSetThreadDefaultOpAttr=libSceFios2_orig.sceFiosSetThreadDefaultOpAttr,@164")
#pragma comment(linker,"/export:sceFiosShutdownAndCancelOps=libSceFios2_orig.sceFiosShutdownAndCancelOps,@165")
#pragma comment(linker,"/export:sceFiosStat=libSceFios2_orig.sceFiosStat,@166")
#pragma comment(linker,"/export:sceFiosStatSync=libSceFios2_orig.sceFiosStatSync,@167")
#pragma comment(linker,"/export:sceFiosSuspend=libSceFios2_orig.sceFiosSuspend,@168")
#pragma comment(linker,"/export:sceFiosTerminate=libSceFios2_orig.sceFiosTerminate,@169")
#pragma comment(linker,"/export:sceFiosTimeGetCurrent=libSceFios2_orig.sceFiosTimeGetCurrent,@170")
#pragma comment(linker,"/export:sceFiosTimeIntervalFromNanoseconds=libSceFios2_orig.sceFiosTimeIntervalFromNanoseconds,@171")
#pragma comment(linker,"/export:sceFiosTimeIntervalToNanoseconds=libSceFios2_orig.sceFiosTimeIntervalToNanoseconds,@172")
#pragma comment(linker,"/export:sceFiosTimeoutElapsed=libSceFios2_orig.sceFiosTimeoutElapsed,@173")
#pragma comment(linker,"/export:sceFiosTraceTimestamp=libSceFios2_orig.sceFiosTraceTimestamp,@174")
#pragma comment(linker,"/export:sceFiosUpdateParameters=libSceFios2_orig.sceFiosUpdateParameters,@175")
#pragma comment(linker,"/export:sceFiosVprintf=libSceFios2_orig.sceFiosVprintf,@176")

// clang-format on
